import{a as q,S,i as c}from"./assets/vendor-b11e2a50.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&y(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function y(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function f(r,e){try{return(await q.get("https://pixabay.com/api/",{params:{key:"44240844-fac6cf8e273222cb69c263295",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:"15"}})).data}catch(o){throw new Error(o.message)}}let u;const v=document.querySelector(".gallery");function m(r){const e=r.map(o=>`
      <li class = "gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}">
        </a>
        
        <ul class="info">
          <li>Likes: ${o.likes}</li>
          <li>Views: ${o.views}</li>
          <li>Comments: ${o.comments}</li>
          <li>Downloads: ${o.downloads}</li>
        </ul>
      </li>
    `).join("");v.insertAdjacentHTML("beforeend",e),u?u.refresh():u=new S(".gallery a",{captionsData:"alt",captionDelay:250})}const p=document.querySelector(".form"),M=document.querySelector(".search-input"),P=document.querySelector(".gallery"),g=document.querySelector(".loader"),d=document.querySelector(".btn");p.addEventListener("submit",$);d.addEventListener("click",B);let n,i,L;async function $(r){if(r.preventDefault(),h(),P.innerHTML="",b(),i=M.value.trim(),!i){c.error({message:"Please enter a search query!",position:"topRight"}),a();return}try{n=1;const e=await f(i,n);if(e&&e.hits&&e.hits.length)a(),L=Math.ceil(e.totalHits/15),w(),m(e.hits);else throw Error("Sorry, there are no images matching your search query. Please try again!")}catch{c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{a()}p.reset()}async function B(){b(),h();try{n+=1;const r=await f(i,n);if(r&&r.hits&&r.hits.length){w(),m(r.hits);const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"});return}else throw new Error("We're sorry, but you've reached the end of search results.")}catch{c.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}finally{a()}}function w(){L>n?R():(h(),c.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}function b(){g.style.display="inline-block"}function a(){g.style.display="none"}function R(){d.classList.remove("hidden")}function h(){d.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
